"""Shared backtest engine: strategy-agnostic simulation + metrics.

Used by both the CLI (backtest.py) and the dashboard API (dashboard.py)
so every run - script or UI - applies identical logic.

Simulation model:
  - fixed quantity per trade (qty shares)
  - orders generated by a strategy execute at the NEXT bar's open
  - optional shorts (allow_short): signal -1 opens a short, +1 covers
  - cost_per_share is charged on every fill (commission + slippage)
  - flat_eod: any open position is force-closed at the last bar of its
    session (day-trading strategies never hold overnight)
"""
import pandas as pd

from strategies import run_strategy


def run_backtest(
    df: pd.DataFrame,
    *,
    strategy: str = "sma_crossover",
    params: dict | None = None,
    qty: int = 10,
    capital: float = 100_000.0,
    allow_short: bool = False,
    cost_per_share: float = 0.0,
    flat_eod: bool = False,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Simulate fixed-quantity trading on the given bars.

    Returns (curve, trades_df). The curve carries Open/High/Low/Close/
    Volume plus signal, order (signal shifted by one bar), shares, cash,
    equity, and eod_exit (side of any forced session-end close).
    """
    df = run_strategy(strategy, df, dict(params or {}))
    df["order"] = df["signal"].shift(1).fillna(0).astype(int)
    df["eod_exit"] = ""
    df["exec"] = ""

    last_of_session = (
        set(df.groupby(df.index.date).tail(1).index) if flat_eod else set()
    )

    cash = float(capital)
    shares = 0
    entry_price = None
    entry_date = None
    entry_side = None
    trades = []

    for idx, row in df.iterrows():
        cost = cost_per_share * qty

        if shares == 0:
            if row["order"] == 1 and cash >= (row["Open"] + cost) * qty:
                shares = qty
                cash -= (row["Open"] + cost) * qty
                entry_price, entry_date, entry_side = row["Open"], idx, "long"
                df.at[idx, "exec"] = "buy"
            elif row["order"] == -1 and allow_short and cash >= (row["Open"] + cost) * qty:
                shares = -qty
                cash += (row["Open"] - cost) * qty
                entry_price, entry_date, entry_side = row["Open"], idx, "short"
                df.at[idx, "exec"] = "sell"
        elif (row["order"] == -1 and shares > 0) or (row["order"] == 1 and shares < 0):
            if shares > 0:
                cash += (row["Open"] - cost) * shares
                pnl = (row["Open"] - entry_price) * shares - 2 * cost * qty
                df.at[idx, "exec"] = "sell"
            else:
                cash -= (row["Open"] + cost) * -shares
                pnl = (entry_price - row["Open"]) * -shares - 2 * cost * qty
                df.at[idx, "exec"] = "buy"
            trades.append(
                {
                    "entry_date": entry_date,
                    "entry_price": entry_price,
                    "exit_date": idx,
                    "exit_price": row["Open"],
                    "side": entry_side,
                    "exit_type": "signal",
                    "pnl": pnl,
                    "costs": 2 * cost * qty,
                }
            )
            shares = 0
            entry_price = entry_date = entry_side = None

        if shares != 0 and idx in last_of_session:
            cost = cost_per_share * qty
            if shares > 0:
                cash += (row["Close"] - cost) * shares
                pnl = (row["Close"] - entry_price) * shares - 2 * cost * qty
                df.at[idx, "eod_exit"] = "sell"
            else:
                cash -= (row["Close"] + cost) * -shares
                pnl = (entry_price - row["Close"]) * -shares - 2 * cost * qty
                df.at[idx, "eod_exit"] = "buy"
            trades.append(
                {
                    "entry_date": entry_date,
                    "entry_price": entry_price,
                    "exit_date": idx,
                    "exit_price": row["Close"],
                    "side": entry_side,
                    "exit_type": "eod",
                    "pnl": pnl,
                    "costs": 2 * cost * qty,
                }
            )
            shares = 0
            entry_price = entry_date = entry_side = None

        df.at[idx, "shares"] = shares
        df.at[idx, "cash"] = cash
        df.at[idx, "equity"] = cash + shares * row["Close"]

    if shares != 0 and entry_price is not None:
        last_close = float(df["Close"].iloc[-1])
        if shares > 0:
            unrealized = (last_close - entry_price) * shares - cost_per_share * qty
        else:
            unrealized = (entry_price - last_close) * -shares - cost_per_share * qty
        trades.append(
            {
                "entry_date": entry_date,
                "entry_price": entry_price,
                "exit_date": None,
                "exit_price": None,
                "side": entry_side,
                "exit_type": "open",
                "pnl": unrealized,
                "costs": cost_per_share * qty,
            }
        )

    trades_df = pd.DataFrame(trades)
    cols = [
        "Open", "High", "Low", "Close", "Volume",
        "signal", "order", "eod_exit", "exec", "shares", "cash", "equity",
    ]
    cols += [c for c in ("sma_fast", "sma_slow") if c in df.columns]
    curve = df[cols].copy()
    curve.index.name = "date"
    return curve, trades_df


def max_drawdown(equity: pd.Series) -> float:
    peak = equity.cummax()
    return float((equity / peak - 1).min())


def compute_metrics(curve: pd.DataFrame, trades_df: pd.DataFrame, capital: float) -> dict:
    equity = curve["equity"]
    final_equity = float(equity.iloc[-1])
    days = max((equity.index[-1] - equity.index[0]).days, 1)
    years = max(days / 365.25, 1e-9)
    n_trades = len(trades_df)
    wins = int((trades_df["pnl"] > 0).sum()) if n_trades else 0
    costs = (
        float(trades_df["costs"].sum())
        if n_trades and "costs" in trades_df.columns
        else 0.0
    )
    return {
        "start": str(curve.index[0].date()),
        "end": str(curve.index[-1].date()),
        "final_equity": round(final_equity, 2),
        "total_return": final_equity / capital - 1,
        "cagr": (final_equity / capital) ** (1 / years) - 1,
        "max_drawdown": max_drawdown(equity),
        "buy_hold": float(curve["Close"].iloc[-1] / curve["Close"].iloc[0] - 1),
        "trades": n_trades,
        "wins": wins,
        "win_rate": wins / n_trades if n_trades else None,
        "costs_total": round(costs, 2),
    }